[project]
name = "browser-automation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Umananda Siddha", email = "umanandasiddha243@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "camoufox[geoip]>=0.5.5",
    "fastapi[standard]>=0.141.1",
    "langgraph>=1.2.11",
    "ollama>=0.6.2",
    "pwdlib[argon2]>=0.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
]
